### PR TITLE
Propagate arguments for implicit attributes to instantiated rules (#137)

### PR DESCRIPTION
**Pull request by mattmoor**
(this runs Travis)

### CODE REVIEW

**Comment by mattmoor** [comment]
cc @erain This is the second stage of the merge process.

**Comment by mattmoor** [comment]
@erain This is consistently failing in the Python e2e test.  I suspect it is broken at head.  Do you want to investigate?

**Comment by erain** [comment]
@mattmoor OK I will investigate first and ask for your help if needed.

**Comment by erain** [comment]
I made some progress on this PR. 

### on the [failing py test](https://travis-ci.org/bazelbuild/rules_k8s/builds/393786046#L1122): 

It looks like the test failed because the K8s was trying to scaling up the replica, so the client couldn't talk to the service. I will restart the test and whether it works this time. 

### on running the tests myself locally

I've got the service account json for the GCP project used for testing, and created a namespace as well as a LoadBalancer service for my $USER. However I still have some proto-related problem so I couldn't successfully run the e2e tests locally in my own namespace. Will keep on trying.

**Comment by erain** [comment]
It looks like retrying the test doesn't solve the problem. Keep debugging why the deployment didn't bring up the pod (once resolve the local test problem).

**Comment by erain** [comment]
It looks like the py_image we built was problematic and would fail to start, and it is the same case if I run the same `./examples/hellogrpc/e2d-test.sh py` from HEAD. 

The image:
```
...
    Image:        us.gcr.io/rules_k8s/travis/us.gcr.io/not-my-project/hello-grpc@sha256:72e9f46c97c9daeff97ca18a2a25e307ada968ba9307aec74455057be43064ef
...
```

To run it locally with docker:

```
yiyu@instance-1:~/opt/rules_k8s$ docker run us.gcr.io/rules_k8s/travis/us.gcr.io/not-my-project/hello-grpc@sha256:72e9f46c97c9daeff97ca18a2a25e307ada968ba9307aec74455057be43064ef
Traceback (most recent call last):
  File "/app/examples/hellogrpc/py/server/server.binary.runfiles/io_bazel_rules_k8s/examples/hellogrpc/py/server/server.py", line 16, in <module>
    import grpc
  File "/app/examples/hellogrpc/py/server/server.binary.runfiles/pypi__grpcio_1_6_0/grpc/__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
  File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 17, in init grpc._cython.cygrpc (src/python/grpcio/grpc/_cython/cygrpc.c:29041)
ImportError: No module named pkg_resources
```

**Comment by fejta** [comment]
Trying to see if I can get confirmation from @ash2k to address the CLA issue.

Need to better understand what the travis job does. Also why aren't the other CI jobs reporting?

/assign @erain @fejta

**Comment by ash2k** [comment]
@fejta https://cla.developers.google.com/clas tells me I'm covered by a corporate agreement for the email address I made the commit with.

**Comment by ash2k** [comment]
And on the original PR the bot did not complain.

**Comment by fejta** [comment]
Dear cla/google context, how do I debug you?

**Comment by erain** [comment]
I was able to fix the mentioned Travis CI problem in #151 . Will get that submitted and come back to this PR.

**Comment by erain** [comment]
Travis CI should be fixed in #152 

I updated this PR branch. Hopefully we will see the tests green so that we can merge this PR.

**Comment by fejta** [comment]
Still seems unhappy, or does that mean that the PR is broken?

```
unable to recognize "STDIN": no matches for kind "Todo" in version "rules-k8s.bazel.io/v1"
```

**Comment by ash2k** [comment]
Now that https://github.com/bazelbuild/rules_k8s/pull/158 is merged (fixing just one of the cases that are addressed here), this PR is no longer correct. If visibility is specified, it will be passed down twice. I can rebase my branch, or someone can update this PR (revert #158).

**Comment by erain** [comment]
Sorry for holding this PR for so long while we are trying to re-establish the PR test process for this repo. 

Rebase this PR would be great if you could help. Many thanks!

**Comment by fejta** [comment]
/override cla/google
See ash2k's comments above, caused by moving his comments into this PR

**Comment by fejta** [comment]
/override cla/google
See ash2k's comments above, caused by moving his comments into this PR

**Comment by nlopezgi** [comment]
/override cla/google
(see comments above)

**Comment by ash2k** [comment]
Rebased my branch: https://github.com/bazelbuild/rules_k8s/pull/165

**Comment by fejta** [comment]
Let's close this out in favor of #165 
/close

**Pull request closed without merging**
