### PR TITLE
Support kubectl --user

### PR DESCRIPTION
**Pull request by mariusgrigoriu**
#### Why this PR is needed

If a user running rules_k8s is setting `cluster` to a value that is not the same as the cluster in their current context, then there is a chance that they also need to set a different user.

#### Approached used

I naively searched for the `cluster` attribute and added matching code for a `user` attribute.

### CODE REVIEW

**Comment by fejta** [comment]
Would https://github.com/bazelbuild/rules_k8s/pull/138 address this need instead?

**Comment by mariusgrigoriu** [comment]
@fejta #138 could address the need with some adaptation on our end to set contexts -- we're overriding namespace, user, and cluster, but don't have a context setup for this specific case. But rules_k8s already supports two out of the three. 

I think this brings me back to the problem statement from #146. Kubectl has many flags and, eventually, we may need access to more and more of them. Seems like replicating all the kubectl flags here is unsustainable.

**Comment by mariusgrigoriu** [comment]
@fejta I think build is broken due to something outside of this PR. Can you confirm?

**Comment by fejta** [comment]
/ok-to-test

> I think build is broken

The job is passing now! 

We're replacing the Travis CI job with its prow equivalent. Your PR won the prize for debugging things.

Forgot it would send a bunch of spam whenever it failed. Apologies and thanks!

**Comment by mariusgrigoriu** [comment]
Still looks like some external issue is blocking the build

**Pull request merged**
