### PR TITLE
Add a Bazel CI Config for rules_k8s.

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes https://github.com/bazelbuild/rules_k8s/issues/6

### CODE REVIEW

**Comment by mattmoor** [comment]
@damienmg Why is this failing?

**Comment by damienmg** [comment]
jenkins: retest this please.

sorry I answered on the rules_docker PR: I think this is a jenkins issue

**Comment by damienmg** [comment]
See it is good now. I rolled-back a change on CI

**Comment by mattmoor** [comment]
@damienmg Do the badges need to change again?

**Comment by damienmg** [comment]
Nope the badges are at the same place.

**Pull request merged**
