### PR TITLE
Don't dump a stack trace when we hit errors publishing images.

### PR DESCRIPTION
**Pull request by mattmoor**
Related to: https://github.com/google/containerregistry/issues/56

### CODE REVIEW

**Comment by mattmoor** [comment]
@vaikas-google FYI

**Comment by mattmoor** [comment]
@dekkagaijin FYI

**Comment by dekkagaijin** [comment]
Looks like k8s/object.bzl needs a reformat:
https://travis-ci.org/bazelbuild/rules_k8s/builds/331471468#L647
```
$ buildifier -mode=check $(find . -name '*.bzl' -type f)
./k8s/object.bzl # reformat 
The command "buildifier -mode=check $(find . -name '*.bzl' -type f)" exited with 4.
```

**Comment by mattmoor** [comment]
Yeah, that looks like a change I optimistically merged from the Bazel folks, which wasn't set up correctly to run our CI (and I figured wouldn't break our integration tests).  (sigh)

This should be RFAL.

**Comment by dekkagaijin** [comment]
Radio-Frequency Assisted Liposuction (RFAL)
Fancy :o

**Comment by mattmoor** [comment]
Bump

**Pull request merged**
