### PR TITLE
Deduplicate transitive objects

### LINKED ISSUE #328: .apply applies the same objects multiple times
When running a `bazel run //:target.apply`, `rules_k8s` will apply some objects multiple times if they happen to be in the graph multiple times:
For instance:
```python
k8s_objects(
    name = "A",
    objects = [
        ":a_object",
        ":B",
        ":C",
    ],
)

k8s_objects(
    name = "B",
    objects = [
        ":b_object",
        ":C",
    ],
)

k8s_objects(
    name = "C",
    objects = [
        ":c_object",
    ],
)
```

Because `A` and `B` both depend on `C`, `C` is applied twice, where it shouldn't.

### PR DESCRIPTION
**Pull request by steeve**
When creating/deleting/applying/... objects, walk the dependency graph
only once. This is done via an aspect that gathers the objects to apply
by detecting rules names that start with "_k8s_object_".

One some complex dependency graphs, this dramatically reduces the apply
time.

Fix #328

### CODE REVIEW

**Comment by nlopezgi** [comment]
Hi @steeve ,
thanks for noticing this issue and for creating this PR.
So, in order to test this you should not need to use the e2e tests. This behavior should be verifiable via bazel tests that can be executed on any platform.
Specifically.
You should be able to add a new `k8s_objects` target to examples/hellogrpc and have it exercise the use case you noted (making sure an object is included multiple times), e.g.:

```
k8s_objects(
    name = "dedupe-object",
    objects = [
        ":staging",
        ":staging-service",
    ],
)
```
You can then write a `file_test` (example in different context: https://github.com/bazelbuild/rules_docker/blob/master/tests/docker/BUILD#L325) that verifies the `dedupe-object.apply` has the expected contents. e.g.:

```
file_test(
    name = "dedupe-test_test",
    content = "staging-deployment.apply",
    file = ":staging.apply",
)
```
iiuc, w/o your PR the dedupe-object.apply would have something like:
```
... /io_bazel_rules_k8s/examples/hellogrpc/staging.apply $@
.../io_bazel_rules_k8s/examples/hellogrpc/staging-service.apply $@
``` 
Whereas after your PR it should have:
```
... /io_bazel_rules_k8s/examples/hellogrpc/staging-deployment.apply $@
.../io_bazel_rules_k8s/examples/hellogrpc/staging-service.apply $@
```

Please let me know if you need more advice

**Comment by steeve** [comment]
Sure thing! I'll find some time to do that this week!

**Comment by nlopezgi** [comment]
Hi @steeve ,
Any updates on this PR, should we close or leave open?

**Comment by steeve** [comment]
Sorry I got sidetracked.
It almost works, but it broke some targets. I'll get to it asap!

**Comment by steeve** [comment]
Closing this one until I have time to fix it! I'll reopen once I update it.

**Pull request closed without merging**
