### PR TITLE
Expand make vars for cluster name (#106)

### PR DESCRIPTION
**Pull request by mattmoor**
* implemented make vars expansion

* added make vars expansion for namespace and image_chroot

### CODE REVIEW

**Comment by mattmoor** [comment]
@schoren FYI

**Comment by schoren** [comment]
That's because I merged from my master right? I can redo it with a different branch if that's the problem

**Comment by mattmoor** [comment]
Just needs buildified.  I'll fix it and merge shortly:
```
buildifier -mode=check $(find . -name '*.bzl' -type f)
./k8s/object.bzl # reformat 
```

**Comment by mattmoor** [comment]
Hmm, I got one of these in [this](https://github.com/bazelbuild/rules_k8s/pull/108) PR too.

**Pull request merged**
