### PR TITLE
[WIP] Update rules_go to 0.16.0

### PR DESCRIPTION
**Pull request by katre**
Needed as part of bazelbuild/bazel#6283.

### CODE REVIEW

**Comment by fejta** [comment]
Please fix the test failures?

**Comment by katre** [comment]
This will not work until https://github.com/pubref/rules_protobuf also updates. I'll ping this PR again once I've gotten them updated.

**Comment by chrislovecnm** [comment]
Marked this as WIP

**Comment by mhlopko** [comment]
PR to update rules_protobuf: https://github.com/pubref/rules_protobuf/issues/248

Waiting for response to see if those rules are still maintained. I don't know much about the protobuf rules and the ecosystem, is there a reason not to use the protobuf provided rules (https://github.com/protocolbuffers/protobuf/blob/master/protobuf.bzl#L219)?

**Comment by pcj** [comment]
I'll look to convert the protobuf rules to minimize dependencies as @mhlopko suggests and otherwise use https://github.com/stackb/rules_proto (successor to https://github.com/pubref/rules_protobuf/) where needed.  ETA 1-2 days.

**Comment by fejta** [comment]
Sounds good thanks for the updates

**Comment by katre** [comment]
I am closing this, since @pcj is handling the update in https://github.com/bazelbuild/rules_k8s/pull/203

**Pull request closed without merging**
