### PR TITLE
Update rules_protobuf to v0.8.1 (depset fixes for bazel 0.6.0)

### PR DESCRIPTION
**Pull request by mattmoor**
Originally: https://github.com/bazelbuild/rules_k8s/pull/39 from @pcj

### CODE REVIEW

**Comment by mattmoor** [comment]
@pcj See the CLA bit above, that's a new one for me :)

**Comment by mattmoor** [comment]
@pcj ping

**Comment by pcj** [comment]
I signed it!

**Comment by pcj** [comment]
Is that not the key phrase the googlebot was looking for?  I signed the CLA quite awhile ago, @katre LMK how I can move this forward.

**Comment by mattmoor** [comment]
I just read the fine print:
> Note to project maintainer: This is a terminal state, meaning the cla/google commit status will not change from this State. It's up to you to confirm consent of the commit author(s) and merge this pull request when appropriate.

I'll merge this now, sorry for nagging you :)

**Comment by mattmoor** [comment]
Ok, I removed some of the GitHub branch protections so that I can merge this.  The buttons are now a scary red :)

**Comment by pcj** [comment]
Not a problem, I learned something, thanks!

**Pull request merged**
