### PR TITLE
Remove broken HTTP E2E test

### PR DESCRIPTION
**Pull request by chases2**

### CODE REVIEW

**Comment by chases2** [comment]
Okay, so obviously I can't retest buildkite tests through prow. Need to figure out how to retry it in-general, though. The failure message `flag provided but not defined: -format` doesn't make it clear what it means in this context.

**Comment by chases2** [comment]
@goodspark These changes together seem to be able to get "pull-rules-k8s-e2e" to pass again. Are you cool with your changes being merged like this? I'd like them to go together.

**Comment by goodspark** [comment]
Sure thing!

**Comment by goodspark** [comment]
@googlebot I consent

**Comment by goodspark** [comment]
@googlebot I consent.

**Review by michelle192837 — APPROVED** [review]

**Pull request merged**
