### PR TITLE
Update the rules_python dependency.

### PR DESCRIPTION
**Pull request by mattmoor**
This pickes up the s/package/requirement/ change.

### CODE REVIEW

**Comment by mattmoor** [comment]
test this please

**Comment by mattmoor** [comment]
please test this

**Comment by mattmoor** [comment]
@damienmg Is something up with Bazel CI?

**Comment by damienmg** [comment]
All slaves were down, restarting them did the trick.

**Comment by damienmg** [comment]
Jenkins: retest this please.

**Pull request merged**
