### PR TITLE
Resolve stamped variables in Kubernetes objects

### PR DESCRIPTION
**Pull request by zoidbergwill**
I was looking at this as work towards fixing https://github.com/bazelbuild/rules_k8s/issues/351

### CODE REVIEW

**Comment by zoidbergwill** [comment]
I got a bit stuck, thinking about how to send the dict of substitutions to the resolver.go to use the stamp-info-file when resolving the substitutions.

I could figure out how to do it in Python, but not Starlark in a rule.

**Comment by rohansingh** [comment]
FYI, I took a shot at this in #505. In terms of this:

> I got a bit stuck, thinking about how to send the dict of substitutions to the resolver.go to use the stamp-info-file when resolving the substitutions.
>
> I could figure out how to do it in Python, but not Starlark in a rule.

I think this is a pretty good idiom for when you want to pass a somewhat complicated structure from Starlark to a binary:

```python
ctx.actions.write(
        output = some_file,
        content = struct(
            key = some_dict,
        ).to_json(),
    )
```

The binary can then read `some_file` and parse it as JSON.

**Comment by zoidbergwill** [comment]
@rohansingh That's a great solution. Will take a look at revisiting this.

**Comment by fejta** [comment]
Please holler when this is ready for review!

**Comment by fejta** [comment]
Please reopen if you get the chance to update it. Closing until then.

**Pull request closed without merging**
