### PR TITLE
Windows compatibility changes

### PR DESCRIPTION
**Pull request by luna-duclos**
This set of changes adds windows compatibility.
The current code is not windows compatible because it directly uses executable bash scripts, which doesn't work on windows (it expects executables).

The fix is not overly difficult, and simply requires us to add sh_binary wrappers to the scripts and to adjust the guess_runfiles functions accordingly.

### CODE REVIEW

**Comment by fejta** [comment]
Please rebase when you get the chance

**Comment by luna-duclos** [comment]
@fejta Change has been rebased

**Comment by fejta** [comment]
Looks like this change breaks on linux

**Comment by luna-duclos** [comment]
It works for me, I dont think the current CI failures are related to my code at all, they appear in other branches too, no ?

**Comment by fejta** [comment]
Tests pass at head. The build failures are on account of your PR

**Comment by fejta** [comment]
(I realize that all the other open PRs are also failing tests, but that is because we merged all the ones that pass tests :) see https://github.com/bazelbuild/rules_k8s/pulls?q=is%3Apr+is%3Aclosed)

So please do look into these failures when you get the chance!


```
ERROR: /home/prow/go/src/github.com/bazelbuild/rules_k8s/examples/hellohttp/java/BUILD:30:11: //examples/hellohttp/java:staging.create.script: no such attribute 'args' in '_k8s_object_create' rule
```

I suspect changing things from an executable to a script is having unintended side effects. I suspect you'll be able to repro on your machine by actually building all targets (`bazelisk build -- ... -//images/gcloud-bazel:gcloud_push -//images/gcloud-bazel:gcloud_installer -//images/gcloud-bazel:gcloud_install -//images/gcloud-bazel:gcloud-layer` as per the buildkite details

**Comment by fejta** [comment]
Would you like to try and fix up this PR or close it?

**Comment by fejta** [comment]
Please rebase and reopen if you're still interested in this

**Pull request closed without merging**
