### PR TITLE
Add resolver to k8s_defaults

### PR DESCRIPTION
**Pull request by samschlegel**
This adds support for setting the default resolver with the `k8s_defaults` rule

### CODE REVIEW

**Comment by chrislovecnm** [comment]
This failed in e2e, and I am not certain why.

```console
customresourcedefinition.apiextensions.k8s.io "todos.rules-k8s.bazel.io" deleted
Error from server: grpc: the client connection is closing
```

**Comment by chrislovecnm** [comment]
@nlopezgi any idea why the other bazel builds are not running??

**Comment by nlopezgi** [comment]
Writing tests for this might be hard as these are workspace repo rules being changed, but lets just double check documentation is up to date and this should be good to submit imo

**Comment by fejta** [comment]
> Writing tests for this might be hard

https://github.com/bazelbuild/rules_k8s/blob/master/examples/hellogrpc/BUILD#L20 etc use k8s_defaults rules... we could just put something to resolve in one of them, and ensure e2e tests continue passing

**Comment by chrislovecnm** [comment]
Because tests are hard we can do another PR, but frankly we need a lot more tests 😞

**Comment by chrislovecnm** [comment]
Can you rebase and do we need any doc changes?

Thanks for your help!

**Comment by chrislovecnm** [comment]
@nlopezgi do we need docs update on this??

**Comment by samschlegel** [comment]
Apologies, I didn't see the updates to this. Let me know if there's anything I need to do

**Comment by chrislovecnm** [comment]
@samschlegel do we need any doc updates?

@nlopezgi can you start build kite CO?

/ok-to-test

**Comment by samschlegel** [comment]
No doc updates are needed, as this is actually already in the docs as being supported :sweat_smile:

**Comment by chrislovecnm** [comment]
Need CI to pass and we can merge this

**Comment by nlopezgi** [comment]
kicked off presubmits, this PR looks good other than the missing doc updates.

**Comment by samschlegel** [comment]
AFAICT no doc updates are needed as this was (erroneously?) added to docs in dc3999f

**Comment by nlopezgi** [comment]
ugh, mac builds are timing out pulling images, will have to figure out tomorrow what's the problem

**Comment by chrislovecnm** [comment]
@nlooezgi can you get this to retest?

**Pull request merged**
