### PR TITLE
Remove kubectl toolchain execution platform constraint

### LINKED ISSUE #215: Toolchain resolution fails with cross-compilation
I'm trying to set cross-compilation, so that I can build locally on a Mac the Go sources to be ran on a local Kubernetes cluster. The kubectl client is running on the Mac.

Running Go compilation as well as creating the Docker image work:

```
$ bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //deploy/docker/user_data:image
INFO: Analysed target //deploy/docker/user_data:image (0 packages loaded).
INFO: Found 1 target...
Target //deploy/docker/user_data:image up-to-date:
  bazel-bin/deploy/docker/user_data/image-layer.tar
INFO: Elapsed time: 0.375s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

However, a wildcard build fails:

```
$ bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //...
ERROR: While resolving toolchains for target //deploy/k8s:user_data_deployment.create: no matching toolchains found for types @io_bazel_rules_k8s//toolchains/kubectl:toolchain_type
ERROR: Analysis of target '//deploy/k8s:user_data_deployment.create' failed; build aborted: no matching toolchains found for types @io_bazel_rules_k8s//toolchains/kubectl:toolchain_type
INFO: Elapsed time: 0.126s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Any hint on how to make k8s work with Go cross-compilation?

Thanks.

### PR DESCRIPTION
**Pull request by pierreis**
Currently, the toolchains defined for kubectl place a constraint on both the target and execution platform. This results in a toolchain resolution failure when both platforms are different, _e.g.,_ by setting the Bazel `--platform` flag.

This PR removes the execution platform constraint from the kubectl toolchain, which is acceptable as the generated binaries are only expected to run on the target platform.

Fixes #215

### CODE REVIEW

**Comment by smukherj1** [comment]
Opened #219 to remove the flaky prow e2e test

**Comment by pierreis** [comment]
Failing at the same point as the last execution of #219.
Hopefully passing once this is merged.

**Comment by pierreis** [comment]
Looks like the e2e test is stuck on waiting for an IP address for the HTTP test, but I don't see it related to the toolchain. Any idea?

**Comment by nlopezgi** [comment]
thanks @fejta we will prioritize higher working on the janitor job

**Comment by fejta** [comment]
It is also possible to configure [the job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/bazelbuild/rules_k8s/rules_k8s_config.yaml) to have a timeout: https://github.com/kubernetes/test-infra/blob/c922083b31bd569e49b473340bffa302f7cd4d1e/config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml#L143-L144

also pushing a new commit and/or a `/test pull-rules-k8s-e2e` should reset the job

Although neither of these things will address the quota issue

**Pull request merged**
