### PR TITLE
Add Tink AB to list of adopters

### PR DESCRIPTION
**Pull request by Sebelino**

### CODE REVIEW

**Comment by Sebelino** [comment]
@googlebot I signed it!

**Review by chases2 — APPROVED** [review]

**Comment by chases2** [comment]
Okay, there's clearly an issue with the integration tests in this repository.

```
++ FAIL: 2=bazel-bin/examples/hellohttp/go/staging.diff
$ /usr/bin/kubectl --kubeconfig= --cluster=gke_rules-k8s_us-central1-f_testing --context=gke_rules-k8s_us-central1-f_testing --user= --namespace=build-1364137601505693696 diff -f -
error: unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta1"
```

It appears to be related to https://github.com/bazelbuild/rules_k8s/issues/637

**Comment by fejta** [comment]
Hope this repo is proving useful to you!

**Pull request merged**
