### PR TITLE
Arbitrary args for kubectl

### PR DESCRIPTION
**Pull request by nlopezgi**
Trying this PR to replace all other PRs discussed in https://github.com/bazelbuild/rules_k8s/issues/209.
With this PR:
- users can add args (string list) to their k8s_deploy object
- users can use bazel run <target> -- <extra args>
- modified templates so the kubectl command is printed out when running bazel run <target>, useful for validation in e2e tests

Hope this satisfies everyone's needs.
fyi @chrislovecnm @Globegitter @omadawn

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Can users have both args defined and pass in args in the cli?

**Comment by nlopezgi** [comment]
> Can users have both args defined in the BUILD fuel and pass in args in the cli?

Yes, in the e2e tests I added both verification for use of args in the attrs defined in the BUILD file as well as one for use of bazel run <target> -- <extra args>
(still fixing the tests/templats to get this working properly)

**Comment by chrislovecnm** [comment]
You gonna rebase? Ping me when the tests are happy and I will merge ;)

**Comment by nlopezgi** [comment]
alright, that was fun to debug. Tests are passing now, ptal.

**Comment by chrislovecnm** [comment]
Harping on this, but do we want to squash the commits on merging? I like to keep master clean so we can easily back out a PR.

**Comment by nlopezgi** [comment]
its set up for squash and merge, so it'll be 1 commit only

**Pull request merged**
