### PR TITLE
Use gcloud builds, and :latest-$USER

### PR DESCRIPTION
**Pull request by fejta**
The UX for `gcloud` changed

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@fejta well I tried to approve 🙄

**Comment by chrislovecnm** [comment]
@fejta WTH is

```
Error from server: context canceled
```

That is what e2e failed on

**Comment by smukherj1** [comment]
Fro the quota logs before attempting the service delete, we see the address usage isn't even close to the limit. So IP address quota doesn't seem to be the issue
Log link: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/bazelbuild_rules_k8s/217/pull-rules-k8s-e2e/384

IP Quota before delete:
- limit: 8.0
  metric: STATIC_ADDRESSES
  usage: 0.0
--
- limit: 16.0
  metric: IN_USE_ADDRESSES
  usage: 2.0
--
- limit: 5.0
  metric: GLOBAL_INTERNAL_ADDRESSES
  usage: 0.0

**Comment by fejta** [comment]
well I guess that answers that..

**Comment by fejta** [comment]
Searching for "context canceled" kubernetes seems to suggest this has something to do with flakes pulling images

**Comment by chrislovecnm** [comment]
@fejta the command to do a single test is not working as well

/retest

**Comment by smukherj1** [comment]
Last failure was a unit test flake
`
==================== Test output for //k8s:resolver_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_prow/0996f4cdf646bf91686374917a22c2ea/sandbox/processwrapper-sandbox/2/execroot/io_bazel_rules_k8s/bazel-out/k8-fastbuild/bin/k8s/resolver_test.runfiles/io_bazel_rules_k8s/k8s/resolver_test.py", line 20, in <module>
    import unittest
  File "/usr/lib/python2.7/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/usr/lib/python2.7/unittest/main.py", line 7, in <module>
    from . import loader, runner
ValueError: bad marshal data (tuple size out of range)
================================================================================
`

**Comment by chrislovecnm** [comment]
Seen this flake before as well 

Error from server: grpc: the client connection is closing
+ echo FAILED, cleaning up...
FAILED, cleaning up..

/retest

**Comment by chrislovecnm** [comment]
The last test seems to be our archilles heal. Should we remove the last test? What value is it??

**Comment by fejta** [comment]
I'm cursed!

**Comment by smukherj1** [comment]
@fejta Worry not. Your savior has arrived with #219. Approve it and thine curse shall begone

**Pull request merged**
