### PR TITLE
Address a few pieces of feedback from @ensonic

### PR DESCRIPTION
**Pull request by mattmoor**
Removes some of the friction from: https://github.com/bazelbuild/rules_k8s/issues/68
Fixes: https://github.com/bazelbuild/rules_k8s/issues/69

### CODE REVIEW

**Comment by mattmoor** [comment]
@ensonic This should enable you to use a much more relaxed set of things as the keys in the images dictionary.  It isn't completely free-form because it still becomes a suffix of the image name, but I also disable strictness, so things like tags can be inferred.

If you could take this for a spin, and LMK what you think I'd appreciate it :)

**Comment by mattmoor** [comment]
@ensonic Were you able to make this work?

**Comment by mattmoor** [comment]
@ensonic LOL, yeah this was one of my original motivations for sticking with strict image names.  I'm not sure how to avoid it without some level of schema-awareness.

**Comment by ensonic** [comment]
Yeah, it is tricky. We should merge this. I've filed a new ticked to discuss the expansion:
https://github.com/bazelbuild/rules_k8s/issues/83

**Pull request merged**
