### PR TITLE
Properly support multi-document yaml files.

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes: https://github.com/bazelbuild/rules_k8s/issues/116

### CODE REVIEW

**Comment by mattmoor** [comment]
@philwo Is CI not set up for this repo?

**Comment by mattmoor** [comment]
@pcj FYI

**Comment by philwo** [comment]
Post- and presubmit checks should now be working for this repo! Please let me know if you encounter any issues.

**Comment by mattmoor** [comment]
@philwo Updating the commit doesn't seem to have made this register with buildkite?

**Comment by buchgr** [comment]
@mattmoor fixed. should work now

**Comment by mattmoor** [comment]
@buchgr Why doesn't this show up the same way it does in `rules_docker?

**Comment by buchgr** [comment]
@mattmoor it will in the next build. you can test it out by just changing the commit hash in this PR (git commit --amend or so).

**Comment by mattmoor** [comment]
FYI, I'm going to ignore the CI failure (I/O failure) since macOS doesn't provide super meaningful coverage for `rules_k8s` and I've shared this with the Bazel team as an example of poor contributor UX.

**Pull request merged**
