### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Vertexwahn**
This PR updates a few dependencies (bazel_skylib and rules_docker)

### CODE REVIEW

**Comment by chases2** [comment]
Looks good overall; please squash your commits together since the intermediate steps don't pass tests.
/assign

**Comment by Vertexwahn** [comment]
@chases2 I squashed the commits

**Comment by chases2** [comment]
Thanks!
/approve
/lgtm

**Comment by Vertexwahn** [comment]
Would expect that "Automation merges the PR"... mmh... something still missing?

**Comment by Vertexwahn** [comment]
@fejta Can you merge the PR?

**Review by michelle192837 — APPROVED** [review]

**Pull request merged**
