### PR TITLE
Add .diff command

### LINKED ISSUE #242: bazel run //path/to:target.diff command
Maybe it is possible and I missed it, but is it possible to do a `.diff` like you would a `.apply`? I'm trying to onboard my free standing YAML configuration into rules_k8s and I believe it will be the same, but it would be nice to know what happens if I were to apply the change in production. Is there anything like that available?

I looked in the docs on this project and also in the docs for `kubectl` to see if I could make the apply command do a diff. It looks like you can get it to do a `--dry-run` but that is entirely local.

### PR DESCRIPTION
**Pull request by samschlegel**
Now that `diff` is released, this adds a `.diff` command. In order to avoid pushing when resolving for the purposes of the diff, this also adds a `no_push` flag to `resolver.py`

Fixes #242

### CODE REVIEW

**Comment by samschlegel** [comment]
:thinking: It's curious that it needs `ok-to-test`, but it looks like the tests ran anyways?

**Comment by smukherj1** [comment]
Hi @samschlegel,

Thanks for your PR. Overall the change looks good. We would like to have a test for this command as well.

I suggest adding it in one of our e2e tests. For example:
1. Add a call to the `diff` command in a bash function like the existing `apply` function [here](https://github.com/bazelbuild/rules_k8s/blob/b3ceedcdfc73711bd32f856bc3992814eb4ae01d/examples/hellohttp/e2e-test.sh#L844).

2. In this new function, validate the output returned by the diff called using `EXPECT_CONTAINS` like [here](https://github.com/bazelbuild/rules_k8s/blob/b3ceedcdfc73711bd32f856bc3992814eb4ae01d/examples/hellohttp/e2e-test.sh#L123).

3. Call the new diff function before the `apply` [here](https://github.com/bazelbuild/rules_k8s/blob/b3ceedcdfc73711bd32f856bc3992814eb4ae01d/examples/hellohttp/e2e-test.sh#L146).

I'm not sure if diff will actually returning any meaningful differences here to validate. The `apply` doesn't changed the resolved configuration, it deploys a new version of the deployed image.

Let me know if you have any questions.

**Comment by nlopezgi** [comment]
Hi @samschlegel ,
is this PR still relevant or can we close?

**Comment by samschlegel** [comment]
Oh no, all of these emails went to the wrong label. This will have to be updated now that the python resolver is gone. Will see if I can fit that in this week

**Comment by zoidbergwill** [comment]
I'd love to see this land, so I made a quick attempt at making it use the Go resolver: https://github.com/bazelbuild/rules_k8s/compare/master...zoidbergwill:add-diff-command?expand=1

I'll test it later today.

**Comment by fejta** [comment]
Any chance you can refresh this PR and/or close it?

**Comment by fejta** [comment]
/close
This looks like a nice features, please consider rebasing and reopening the PR

**Pull request closed without merging**
