### PR TITLE
Do not use constraints from bazel_tools

### LINKED ISSUE #674: Do not use constraints from bazel_tools
Constraints from bazel_tools should not be used, instead the ones from https://github.com/bazelbuild/platforms should be used. In Bazel 5.0 this will be flipped and already now to prepare the migration to Bazel 5.0 someone depending on rules_docker cannot flip the flag because rules_docker still uses bazel_tools.
More info in: bazelbuild/bazel#8622

### PR DESCRIPTION
**Pull request by limdor**
Fixes #674

### CODE REVIEW

**Comment by limdor** [comment]
@fejta any updates on this? Without this it is not possible to use Bazel 5 with the default flags.

**Comment by limdor** [comment]
@fejta @chases2 gentle ping

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
@chases2 Can you or any other owner of rules_k8s take a look before merging this?

**Review by chases2 — APPROVED** [review]

**Comment by limdor** [comment]
Thanks a lot!

**Pull request merged**
